/**
* Linkmark
* Linkmark
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.honwakalab.linkmark.apiclient.linkmark.model

import dev.honwakalab.linkmark.apiclient.linkmark.model.Tag

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 * @param id 
 * @param url 
 * @param tags 
 */
@Serializable
data class Link (
    @SerialName(value = "id")
    val id: kotlin.Long,
    @Contextual @SerialName(value = "url")
    val url: java.net.URI,
    @SerialName(value = "tags")
    val tags: kotlin.collections.List<Tag>
)

