/**
* Linkmark
* Linkmark
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.honwakalab.linkmark.apiclient.linkmark.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 * @param id 
 * @param name 
 */
@Serializable
data class Tag (
    @SerialName(value = "id")
    val id: kotlin.Long,
    @SerialName(value = "name")
    val name: kotlin.String
)

